import pandas as pd
from pathlib import Path

from analytics import build_improvement_plan, diagnose, quantify_opportunities, standardize, suggest_mapping
from ingestion import build_semantic_layer, clean_unformatted_table, demo_source_tables
from knowledge import actionable_frontline_insights, add_frontline_actions, demo_frontline_knowledge, structure_observation


def test_sample_data_matches_expected_diagnostic_profile():
    raw = pd.read_csv("sample_factory_data.csv")
    result = diagnose(standardize(raw, suggest_mapping(raw.columns)))

    assert round(result.metrics["ftt"], 3) == 0.851
    assert round(result.metrics["avg_changeover_minutes"], 1) == 62.5
    assert result.opportunities.iloc[0]["Metric"] == "Average changeover"


def test_alias_mapping_accepts_common_client_headers():
    raw = pd.DataFrame({
        "Day": ["2026-01-01"],
        "Target": [100],
        "Actual": [90],
        "First Pass Good": [80],
        "Rejects": [2],
    })
    mapping = suggest_mapping(raw.columns)
    standardized = standardize(raw, mapping)

    assert set(["date", "planned_units", "produced_units", "good_first_pass_units", "rejected_units"]).issubset(standardized.columns)


def test_value_register_and_improvement_cycle_are_created():
    raw = pd.read_csv("sample_factory_data.csv")
    result = diagnose(standardize(raw, suggest_mapping(raw.columns)))
    register = quantify_opportunities(result)
    plan = build_improvement_plan(register)

    assert not register.empty
    assert register["Annual loss exposure (£)"].sum() > 0
    assert plan.iloc[0]["ID"] == "CI-001"
    assert set(["Owner", "Status", "Actual", "Next review", "Evidence / learning"]).issubset(plan.columns)


def test_ingestion_detects_buried_header_and_builds_semantic_layer():
    messy = pd.DataFrame([
        ["Weekly production export", None, None],
        ["generated by ERP", None, None],
        ["Day", "Target", "Actual"],
        ["2026-01-01", 100, 90],
    ])
    cleaned, header_row = clean_unformatted_table(messy)
    assert header_row == 3
    assert list(cleaned.columns) == ["Day", "Target", "Actual"]


def test_demo_raw_pack_consolidates_to_required_semantics():
    tables, evidence, warnings = demo_source_tables(Path("sample_factory_data.csv"))
    ingested = build_semantic_layer(tables, evidence, warnings)

    assert not ingested.semantic_data.empty
    assert set(["date", "planned_units", "produced_units", "good_first_pass_units", "rejected_units"]).issubset(ingested.semantic_data.columns)
    assert int(ingested.semantic_data["produced_units"].sum()) == 11350
    assert len(ingested.evidence_register) == 1


def test_frontline_knowledge_requires_validation_before_creating_insights():
    knowledge = demo_frontline_knowledge()
    insights = actionable_frontline_insights(knowledge)

    assert set(insights["Source IDs"].str.cat(sep=", ").replace(",", "").split()).issuperset({"FK-001", "FK-002"})
    assert not insights["Source IDs"].str.contains("FK-003").any()


def test_new_observation_is_pending_and_validated_knowledge_seeds_actions():
    knowledge = structure_observation(
        demo_frontline_knowledge(), "Maintenance", "Line 1", "Maintenance",
        "The bearing noise returned after the last adjustment.", "Technician", "Voice note",
    )
    assert knowledge.iloc[-1]["Validation"] == "Pending review"

    knowledge.loc[knowledge["ID"] == "FK-004", "Validation"] = "Validated"
    insights = actionable_frontline_insights(knowledge)
    plan = add_frontline_actions(pd.DataFrame(columns=build_improvement_plan(pd.DataFrame()).columns), insights)
    assert not plan.empty
    assert plan["Evidence / learning"].str.contains("Frontline evidence").all()
